### ISSUE TITLE
Lower NuGet requirement to 2.8.1

### ISSUE THREAD

**Issue by jamesmontemagno** [dsplaisted/PCLStorage#2]
Xamarin studio is only 2.8.1 :(

**Comment by dsplaisted** [comment]
NuGet 2.8.3 is required for Xamarin.iOS unified framework support.  I'm guessing the version of NuGet in Xamarin studio supports this framework.  Do you know if there's any reason it's not labeled as 2.8.3?

**Comment by jamesmontemagno** [comment]
Yes, 2.8.3 is required in VS for Unified, but we have not upgraded Xamarin Studio to 2.8.3, it is only 2.8.1 currently and we are working on it. Xamarin Studio support Unified just fine, but you have to set your minimum requirement to 2.8.1 for anyone to install it in XS. It is unfortunate, but I don't have a timeline when we will make the jump to 2.8.3. So temporarily you should set it to 2.8.1 or no one using XS will be able to use the package as it will error out.

**Comment by jamesmontemagno** [comment]
Any update on this at all?
