### ISSUE TITLE
Is this project Dead. 

### ISSUE THREAD

**Issue by jcphlux** [dsplaisted/PCLStorage#27]
I am trying to decide if I should use it or not.

**Comment by dsplaisted** [comment]
There's not much activity on it currently, but I don't think there needs to be.  It does something fairly simple and I think it works well.

https://twitter.com/dsplaisted/status/676555269308997632

If you feel like it's missing something let me know, and I'm always happy to consider pull requests.

**Comment by soroshsabz** [comment]
ITNOA

Hi,

So why you do not accept pull requests in pull requests queue for a long time?
