### ISSUE TITLE
.NET Standard support

### ISSUE THREAD

**Issue by BartoszCichecki** [dsplaisted/PCLStorage#53]
Do you have any idea when .NET Standard support will be added?

**Comment by tiksn** [comment]
Looks like repository is not supporting

**Comment by assassin316** [comment]
@dsplaisted  Is this project still active?  Any planned support for .Net Standard?

**Comment by laurentiustamate94** [comment]
If this is still relevant, I've rewritten the plugin targeting Xamarin NetStandard in my [repo](https://github.com/laurentiustamate94/netstandard-storage)

**Comment by assassin316** [comment]
@laurentiustamate94  thanks for the info!  :)
